security:
  basic:
    enabled: true
  user:
    name: user
    password: password123
server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hanguanlan1/SpringCloudConfig